'use strict'
try{
    x = 10;
}
catch(error){
    console.log(error)
    
}
finally{
    //Siempre se va a ejecutar. 
    console.log("Termina revision de Errores. ")

}

